// This file is typically auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > lib/supabase/database.types.ts

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            identities: {
                Row: {
                    id: string
                    user_id: string
                    who_you_want_to_be: string
                    core_values: string[]
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    who_you_want_to_be: string
                    core_values: string[]
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    who_you_want_to_be?: string
                    core_values?: string[]
                    created_at?: string
                    updated_at?: string
                }
            }
            scorecard_items: {
                Row: {
                    id: string
                    user_id: string
                    habit_name: string
                    rating: 'positive' | 'negative' | 'neutral'
                    notes: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    habit_name: string
                    rating: 'positive' | 'negative' | 'neutral'
                    notes?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    habit_name?: string
                    rating?: 'positive' | 'negative' | 'neutral'
                    notes?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            habits: {
                Row: {
                    id: string
                    user_id: string
                    name: string
                    identity_reason: string
                    action: string
                    time_of_day: string
                    location: string
                    two_minute_version: string
                    cue: string
                    context: string | null
                    habit_stacking: string | null
                    temptation_bundling: string | null
                    emotional_why: string | null
                    anticipated_reward: string | null
                    friction_reducers: string[] | null
                    friction_adders_for_bad: string[] | null
                    immediate_reward: string | null
                    frequency: 'daily' | 'weekly' | 'custom'
                    target_days: Json | null
                    routine_type: 'morning' | 'evening' | 'anytime'
                    is_active: boolean
                    current_streak: number
                    longest_streak: number
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    name: string
                    identity_reason: string
                    action: string
                    time_of_day: string
                    location: string
                    two_minute_version: string
                    cue: string
                    context?: string | null
                    habit_stacking?: string | null
                    temptation_bundling?: string | null
                    emotional_why?: string | null
                    anticipated_reward?: string | null
                    friction_reducers?: string[] | null
                    friction_adders_for_bad?: string[] | null
                    immediate_reward?: string | null
                    frequency?: 'daily' | 'weekly' | 'custom'
                    target_days?: Json | null
                    routine_type?: 'morning' | 'evening' | 'anytime'
                    is_active?: boolean
                    current_streak?: number
                    longest_streak?: number
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    name?: string
                    identity_reason?: string
                    action?: string
                    time_of_day?: string
                    location?: string
                    two_minute_version?: string
                    cue?: string
                    context?: string | null
                    habit_stacking?: string | null
                    temptation_bundling?: string | null
                    emotional_why?: string | null
                    anticipated_reward?: string | null
                    friction_reducers?: string[] | null
                    friction_adders_for_bad?: string[] | null
                    immediate_reward?: string | null
                    frequency?: 'daily' | 'weekly' | 'custom'
                    target_days?: Json | null
                    routine_type?: 'morning' | 'evening' | 'anytime'
                    is_active?: boolean
                    current_streak?: number
                    longest_streak?: number
                    created_at?: string
                    updated_at?: string
                }
            }
            bad_habits: {
                Row: {
                    id: string
                    user_id: string
                    name: string
                    cue: string
                    craving: string
                    response: string
                    reward: string
                    make_invisible: string | null
                    make_unattractive: string | null
                    make_difficult: string | null
                    make_unsatisfying: string | null
                    is_active: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    name: string
                    cue: string
                    craving: string
                    response: string
                    reward: string
                    make_invisible?: string | null
                    make_unattractive?: string | null
                    make_difficult?: string | null
                    make_unsatisfying?: string | null
                    is_active?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    name?: string
                    cue?: string
                    craving?: string
                    response?: string
                    reward?: string
                    make_invisible?: string | null
                    make_unattractive?: string | null
                    make_difficult?: string | null
                    make_unsatisfying?: string | null
                    is_active?: boolean
                    created_at?: string
                    updated_at?: string
                }
            }
            habit_logs: {
                Row: {
                    id: string
                    habit_id: string
                    user_id: string
                    completed: boolean
                    log_date: string
                    notes: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    habit_id: string
                    user_id: string
                    completed?: boolean
                    log_date: string
                    notes?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    habit_id?: string
                    user_id?: string
                    completed?: boolean
                    log_date?: string
                    notes?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            [_ in never]: never
        }
        Enums: {
            [_ in never]: never
        }
    }
}